### ISSUE TITLE
Looks like a password in your code

### ISSUE THREAD

**Issue by ff6347** [FabiGu/WalkWithMe#1]
https://github.com/FabiGu/WalkWithMe/blob/master/js/main.js#L17

**Comment by 256dpi** [comment]
Yes, we know, we will change it soon.
Thanks for letting us know.

Btw: How are things? ;)

**Comment by ff6347** [comment]
Things are good here in Berlin. Thanks for asking. We are getting reinforcements at home. Somebody to teach everything from scratch. 👪

**Comment by 256dpi** [comment]
Congratulations! Let's talk soon, i'm curious how the IoT course went.
